import "./globals.css";
import '@fontsource/poppins'; 

export const metadata = {
  title: "Wrirk",
  description: "Generated by wrirk",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-poppins">{children}</body>
    </html>
  );
}
